#!/usr/bin/env node
var WebSocketClient = require('websocket').client;

var client = new WebSocketClient();
client.on('connectFailed', function (error) {
	console.log('ERROR ' + error.toString());
});

client.on('connect', function (connection) {
	console.log('connect');
	connection.on('error', function (error) {
		console.log('error ' + error.toString());
	});
	connection.on('close', function (reasonCode, description) {
		console.log('close ' + reasonCode.toString() + ' ' + description);
		console.log('reconnect');
		client.connect(process.argv[2]);
	});
	connection.on('message', function (message) {
		if (message.type === 'utf8') {
			console.log('message ' + message.utf8Data);
		}
	});
});

client.connect(process.argv[2]);
